services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            SERVER_NAME: ':${APP_PORT:-80}'
        volumes:
            - '.:/app'
            - 'todoapp-vendor:/app/vendor'
        networks:
            - todoapp
        depends_on:
            - mysql
            - mailpit
    node:
        image: 'node:22'
        ports:
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        volumes:
            - '.:/app'
        working_dir: '/app'
        tty: true
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-password}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE:-laravel}'
            MYSQL_USER: '${DB_USERNAME:-laravel}'
            MYSQL_PASSWORD: '${DB_PASSWORD:-password}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'todoapp-mysql:/var/lib/mysql'
        networks:
            - todoapp
    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - todoapp
    playwright:
        image: 'mcr.microsoft.com/playwright:v1.47.0-jammy'
        ipc: host
        environment:
            PLAYWRIGHT_HTML_HOST: '0.0.0.0'
            APP_ENV: 'docker'
        ports:
            - '9323:9323'
        volumes:
            - '.:/app'
        working_dir: '/app'
        networks:
            - todoapp
networks:
    todoapp:
        driver: bridge
volumes:
    todoapp-mysql:
        driver: local
    todoapp-vendor:
        driver: local
