name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  playwright-tests:
    env:
      TZ: 'Asia/Tokyo'
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Initialize application
        run: |
          cp .env.ci .env
          docker compose build
          docker compose up -d
          docker compose exec php composer install
          docker compose exec node sh -c "npm ci && npm run build"
          npx playwright install --with-deps

      - name: Migrate
        run: |
          max_retries=60
          retries=0
          until (docker compose ps mysql | grep -q "healthy") || [ $retries -eq $max_retries ]; do
            echo "$service_name starting: $(docker compose ps "$service_name" | grep "$service_name")"
            sleep 1
            retries=$((retries+1))
          done
  
          if [ $retries -eq $max_retries ]; then
            echo "Services did not become healthy in time"
            docker compose ps
            exit 1
          fi

          docker compose exec php php artisan migrate --seed --force

      - name: Run Playwright tests
        run: |
          npx playwright test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
